services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: simadok-laknis-app
    container_name: simadok-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - simadok-network
    depends_on:
      db:
        condition: service_healthy # App menunggu DB siap 100%

  web:
    image: nginx:alpine
    container_name: simadok-web
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - simadok-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: simadok-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simadok_db
      MYSQL_ROOT_PASSWORD: password_rahasia_root # Ganti dengan password yang kuat
      MYSQL_USER: simadok_user
      MYSQL_PASSWORD: password_simadok # Ganti juga ini
    volumes:
      - simadok_db_data:/var/lib/mysql # Brankas permanen Docker
    networks:
      - simadok-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  simadok-network:
    driver: bridge

volumes:
  - ./:/var/www
  - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
